[api]
base_url = "http://16.171.235.240"
timeout = 30
max_retries = 3

[app]
title = "Classification de Produits CLIP"
description = "Application de classification de produits utilisant CLIP et Streamlit"
version = "1.0.0"

[accessibility]
color_blind_mode = false
high_contrast = false
large_text = false
